export default {
  BASE_URL: "http://146.190.17.79:9000/api/",
  SIGN_IN: "singin",
  SIGN_UP: "signup",
  FORGOT_PASSWORD: "forgotpassword",
  CHANGE_PASSWORD: "changepassword",
  HOME: "home",
  SURVEY_INTRO: "surveyintro",
  QUESTIONS: "questions",
  CHAT: "chat",
  DOCTOR_DASHBOARD: "doctordashboard",
  DOCTOR_PENDING_SURVEYS: "doctorpandingsurveys",
  DOCTOR_PENDING_SURVEY_DETAIL: "doctorpandingsurveydetail",
  DOCTOR_CHAT_LIST: "doctorchatlist",
  PRESCRIPTION: "prescription",
  SPLASH: "splash",
  DOCTORS_NAVIGATOR: "doctorsnavigator",
  PATIENT_NAVIGATOR: "patientnavigator",
  DOCTOR_CHAT: "doctorchat",
};
